// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC13s7MAYX-fm4lJsy9a-CYiBNPc-4XoE',
    appId: '1:863871629779:web:467b065911d71caf805726',
    messagingSenderId: '863871629779',
    projectId: 'chatapp-fd362',
    authDomain: 'chatapp-fd362.firebaseapp.com',
    storageBucket: 'chatapp-fd362.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-WgiPoo4BwA6SOy3-nbp7_S15RhoH5k0',
    appId: '1:863871629779:android:ff9702726b286f7b805726',
    messagingSenderId: '863871629779',
    projectId: 'chatapp-fd362',
    storageBucket: 'chatapp-fd362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_8YIQ1B_aHAnBGhuEF3Ucsf579xCK2j0',
    appId: '1:863871629779:ios:8a9783bd0aa2fc49805726',
    messagingSenderId: '863871629779',
    projectId: 'chatapp-fd362',
    storageBucket: 'chatapp-fd362.firebasestorage.app',
    iosClientId: '863871629779-n23oahsh8squkhur59ej7r6qcg33o2ml.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_8YIQ1B_aHAnBGhuEF3Ucsf579xCK2j0',
    appId: '1:863871629779:ios:8a9783bd0aa2fc49805726',
    messagingSenderId: '863871629779',
    projectId: 'chatapp-fd362',
    storageBucket: 'chatapp-fd362.firebasestorage.app',
    iosClientId: '863871629779-n23oahsh8squkhur59ej7r6qcg33o2ml.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC13s7MAYX-fm4lJsy9a-CYiBNPc-4XoE',
    appId: '1:863871629779:web:eb40c15f215dac1f805726',
    messagingSenderId: '863871629779',
    projectId: 'chatapp-fd362',
    authDomain: 'chatapp-fd362.firebaseapp.com',
    storageBucket: 'chatapp-fd362.firebasestorage.app',
  );
}
